---
abstract: 'Add "inline" keyword to declare inline subs'
author:
  - 'Peter Martini <pcm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Inline
no_index:
  directory:
    - t
requires: {}
version: 0.01
